name: HdB

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        # date +%s ==> seconds since the Epoch (1970-01-01 00:00 UTC)
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      
      - name: Install dependencies
        run: python -m pip install pytest Flask-Testing SQLAlchemy flask_sqlalchemy
            
      - name: Run tests
        run: PYTHONPATH=$PYTHONPATH:. pytest
